# Change this name to something that makes sense for your project
name: template-drupal8

# Excludes rarely edited folder / files to win performance.
excludes:
  - drush
  - scripts
  - vendor
  - web/core
  - web/modules/contrib
  - web/profiles/contrib
  - web/sites/default/files
  - web/themes/contrib

# Use the recipe appropriate for your application.
recipe: platformsh

# Replace with your p.sh ID.
config:
  id: REPLACE-ME
  variables:
    app:
      php:
        xdebug.remote_connect_back: 1

tooling:
  drush:
    service: app
    cmd: /app/vendor/bin/drush --root=/app/web
